### ISSUE TITLE
kml -> geojson

### ISSUE THREAD

**Issue by bdon** [sheethub/tpe3d#1]
Hi, is there anywhere on GitHub I can find the kml -> geojson processing for the building files?

**Comment by ronnywang** [comment]
我剛剛把程式碼也都上傳了

crawler.php 把完整的檔案全部下載下來，並放到 kmzs/ 資料夾下 (不過為避免 DDoS 台北市政府，建議這程式不需要自行執行，我會再把已下載的檔案丟到 Dropbox 上面)
dae-geojson.php 把 kmzs/ 資料夾下的所有 kmz 中的 dae 檔解出來，並且算成 geojson
geojsons/ 這邊已經是處理好的所有 geojson

**Comment by ronnywang** [comment]
https://www.dropbox.com/s/afj88qjj4gyk7y8/kmzs.zip?dl=0

完整的 kmzs/ 下的檔案

**Comment by bdon** [comment]
:+1: thanks

**Comment by bdon** [comment]
I started to create a workflow around eventually importing the files into OSM here

https://github.com/bdon/tpe_building_import

Thanks for the scripts, It made parsing the KMZs much easier. I did make one change which was doing the unprojection of models into geographic coordinates via TWD97, which seems to correct some intersection issues (EDIT: nevermind, different error)
Maybe you'll find it useful
