### ISSUE TITLE
讚讚讚！感謝你們保存了這些資料

### ISSUE THREAD

**Issue by surfine** [sheethub/tpe3d#2]
現在再去下載的話，只會重定向至 3d.taipei。

<script type="text/javascript">    document.location.href = "http://3d.taipei";</script>

**Comment by ronnywang** [comment]
有嗎? 我剛剛試了 http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/Taipei3DBuilding_nl.kml 還可以下載沒有問題?

從 http://data.taipei/opendata/datalist/datasetMeta/preview?id=9b7d78d2-0d73-4b42-9b29-c1640efed0eb&rid=7b5efd32-52c5-420e-8c0f-d86ef54f0cd9 過去的

**Comment by surfine** [comment]
你試一下一路從 http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/4352.kml、http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/3948_nl.kml、http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/3948_r15.kmz 下載下來試試看？

**Comment by ronnywang** [comment]
http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/4352.kml  、http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/3948_nl.kml  、http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/3948_r15.kmz 

因為你的頓號跟網址連在一起了，所以整個被當成是同一個網址了
把他空一格就沒問題了

**Comment by surfine** [comment]
頓號不是網址的一部分啊…「、」「、」「、」看不懂？

**Comment by ronnywang** [comment]
http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/4352.kml 
http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/3948_nl.kml
這樣是兩個網址

但是如果你打
「http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/4352.kml 、http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/3948_nl.kml」

兩個網址之間沒任何空白，只用全形頓號分開
github 就以為他只是一個更長的網址，後面變成 「4352.kml、http://adm.....」
於是就找不到網頁導到 3d.taipei 去了

**Comment by surfine** [comment]
都說不是這個問題，以上僅是表達上的錯誤而已⋯

**Comment by ronnywang** [comment]
不好意思我會錯意了

不過我剛剛試
http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/4352.kml
http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/3948_nl.kml 
http://adm3d.taipei.gov.tw/tcg/kml/Taipei3DBuilding/4352/3948_r15.kmz
這三個連結都是可以正常下載的

不好意思會針對這問題一直回覆是因為我沒有預期這資料集會被臺北市政府下架
這個 repo 的主要目的不是備份這些資料，而是想要給要使用這些資料的人節省下轉檔的功夫
如果臺北市政府真的把這資料下架的話，我會想直接對市府詢問下架的原因

**Comment by surfine** [comment]
有可能與 Google Earth API 終止服務有關? 我這邊也是有的可以下，有的重定向

**Comment by surfine** [comment]
無論如何 誤會一場 相信市府無意撤回這些資料，只是對下載內容不完全可用（有的是model，有的是重定向）感到奇怪，不知道跟 firewall 有沒有關係
